# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Gandalf"                                # Your name
  description: "Gandalf is a renowned wizard and scholar of Middle-earth"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Photography"
        href: photography/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: folder-symlink
        href: https://www.willamette.edu
      - icon: twitter
        href: https://twitter.com/
      - icon: linkedin
        href: https://www.linkedin.com/
      - icon: envelope
        aria-label: email
        href: "mailto:email@willamette.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2024 Blitz</span>
    center: |
      <span class="faux-block"><a href="https://www.willamette.edu">Visit Willamette.edu!</a></span>
    right: |
      <span class="faux-block"><a href="https://www.willamette.edu/">Visit My GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true